"""изменение часового пояса

Revision ID: 9ac42cf0f029
Revises: 9e3cc02e7f10
Create Date: 2024-01-06 06:36:24.509974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac42cf0f029'
down_revision = '9e3cc02e7f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('initiatives', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('initiatives', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
